# Generated by Django 4.2.6 on 2023-11-25 05:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="cover_photo",
            new_name="thumbnail",
        ),
    ]
