# Generated by Django 4.2.6 on 2023-12-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_rename_cover_photo_event_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Don't write anything in this field. It will automatically generate when you save this.",
                unique=True,
            ),
        ),
    ]
