# Generated by Django 5.0.1 on 2024-01-24 20:08

import diucpc.committees.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Committee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        upload_to=diucpc.committees.utils.committee_photo_path
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("student", "Student"), ("teacher", "Teacher")],
                        max_length=10,
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        choices=[
                            ("2020", "2020"),
                            ("2021", "2021"),
                            ("2022", "2022"),
                            ("2023", "2023"),
                            ("2024", "2024"),
                            ("2025", "2025"),
                            ("2026", "2026"),
                            ("2027", "2027"),
                            ("2028", "2028"),
                            ("2029", "2029"),
                            ("2030", "2030"),
                            ("2031", "2031"),
                            ("2032", "2032"),
                            ("2033", "2033"),
                            ("2034", "2034"),
                            ("2035", "2035"),
                            ("2036", "2036"),
                            ("2037", "2037"),
                            ("2038", "2038"),
                            ("2039", "2039"),
                            ("2040", "2040"),
                            ("2041", "2041"),
                            ("2042", "2042"),
                            ("2043", "2043"),
                            ("2044", "2044"),
                            ("2045", "2045"),
                            ("2046", "2046"),
                            ("2047", "2047"),
                            ("2048", "2048"),
                            ("2049", "2049"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="committee",
            constraint=models.UniqueConstraint(
                fields=("type", "year"), name="unique_committee"
            ),
        ),
    ]
