# Generated by Django 5.0.1 on 2024-01-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Carousels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alt", models.CharField(blank=True, max_length=200)),
                ("image", models.ImageField(upload_to="carousels/")),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
