# Generated by Django 4.2.6 on 2023-11-25 05:47

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
