# Generated by Django 4.2.6 on 2023-11-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("associative", "Associative"),
                    ("executive", "Executive"),
                    ("core", "Core"),
                ],
                default="general",
                max_length=20,
            ),
        ),
    ]
