# Generated by Django 5.0.1 on 2024-01-24 20:08

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Don't write anything in this field. It will automatically generate when you save this.",
                        unique=True,
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="cover/"),
                ),
                (
                    "description",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True
                    ),
                ),
                ("speaker_name", models.CharField(max_length=100)),
                ("speaker_designation", models.TextField(blank=True, null=True)),
                ("registration_link", models.URLField(blank=True, null=True)),
                ("registration_note", models.TextField(blank=True, null=True)),
                ("platform", models.TextField(blank=True, null=True)),
                ("started_date", models.DateField(blank=True, null=True)),
                ("ended_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "draft"), ("published", "published")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
