# Generated by Django 5.0.1 on 2024-01-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="ended_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="started_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
